### ISSUE TITLE
SyncBN?

### ISSUE THREAD

**Issue by jizongFox** [HobbitLong/SupContrast#18]
Hi @HobbitLong 

I see you use `SyncBN` from apex to train with `DataParallel`, however, `SyncBN` seems to be designed with `DistributedDataParallel`. Could you please confirm if `SyncBN` works in this case?

Best,
Jizong

**Comment by HobbitLong** [comment]
@jizongFox, I did not realize it. Maybe you are right then that the code probably only used normal BN.

**Comment by QuetzalcoatlRosso** [comment]
Are there any accuracy metrics that may be negatively impacted if syncbn is off and apex is not used at all?

**Comment by zcy5417** [comment]
作者你这也太坑了

**Comment by jizongFox** [comment]
> 作者你这也太坑了

????? what are you talking about?

**Comment by zcy5417** [comment]
> > 作者你这也太坑了
> 
> ????? what are you talking about?

我说作者坑啊，又没说你

**Comment by zcy5417** [comment]
> > > 作者你这也太坑了
> > 
> > 
> > ????? what are you talking about?
> 
> 我说作者坑啊，又没说你

SyncBN可能都没起到作用，论文的数据不就是有问题的吗
