### ISSUE TITLE
L2 normalization not performed in the code?

### ISSUE THREAD

**Issue by nishraptor** [HobbitLong/SupContrast#22]
Hi,

Where do you perform L2 normalization in the code? Is this something that needs to be done separately? Currently running into nan losses in my current dataset, and i'm trying to figure out if that is the reason.

**Comment by HobbitLong** [comment]
L2 normalization is done [here](https://github.com/HobbitLong/SupContrast/blob/master/networks/resnet_big.py#L185).

**Comment by nishraptor** [comment]
Hi,

Thanks! I fixed it by running my batch size at 1024 instead of 256. Also, for anyone who is wondering, If you want to use some other architecture other than the ones here, remember to l2 norm your output before passing to SupConLoss.
