### ISSUE TITLE
about SupConLoss

### ISSUE THREAD

**Issue by Dingkx9** [HobbitLong/SupContrast#23]
appreciate of your great work! I wanna figrue out contrast_count = features.shape[1],the value of fetures.shape[1] is n_views,and I 
can't understand what n_views represent.Is it always eaual to 2?

**Comment by HobbitLong** [comment]
`n_views` can be larger than 2, and it represents how many different views (or augmentations) from each image.

Here we just used two crops from each image, but you can go beyond 2.

**Comment by Dingkx9** [comment]
Okay. Thank u for ur reply

**Comment by prashkmr** [comment]
can n-view not be 1 only; given we have other positives of the same class to contrast with, too.
