### ISSUE TITLE
Final output of the loss

### ISSUE THREAD

**Issue by zhangdan8962** [HobbitLong/SupContrast#24]
Hi, I am wondering what is the point for the following line? And can I just simply call loss.mean()?

https://github.com/HobbitLong/SupContrast/blob/d566677b34762951c05d43f011f60be7ee2c594e/losses.py#L96

**Comment by HobbitLong** [comment]
Hi, @zhangdan8962,

The purpose is simply showing "bsz" is the second dimension instead of the first one, in case that someone else will further manipulate on this to achieve per-sample loss. You can ignore or remove it if you don't care about it.
