### ISSUE TITLE
Questions about DataParallel 

### ISSUE THREAD

**Issue by killandy** [HobbitLong/SupContrast#36]
As the model uses the DataParallel with k GPUs, the BatchSize m will be split into k parts (m = n*k) and then gather the gradients for backward. 
So is the loss computed in the batch m (with more negative samples) or the small parts n (with less negative samples).

**Comment by HobbitLong** [comment]
In batch m, since features will be gathered on the first GPU to perform the loss.

**Comment by killandy** [comment]
(^_^)Thanks.
