### ISSUE TITLE
Visualization results with t-sne

### ISSUE THREAD

**Issue by Hiiragi0107** [HobbitLong/SupContrast#39]
Hello.
Thank you for providing me with great code.
I would like to see the results of the visualization when I actually run it myself.
It would be great if you could provide me with the code to visualize using t-sne.
Thank you for your help.

**Comment by zhangdan8962** [comment]
@Hiiragi0107 Did you figure out the code?

**Comment by DinSangrasi** [comment]
No, I requested the author, he denied.

If u get that kindly email me .
Cheers
________________________________

**Comment by zhangdan8962** [comment]
Did he mention the values of parameters for TSNE or other tricks?

**Comment by DinSangrasi** [comment]
He didn't mention any such thing, all he said that he has written a new version of tune which will be released later, not now. Just wondering,  are u also working on sup contrastive loss?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zhangdan8962** [comment]
No, I am working on general self-supervised learning. But I have not figured out how to visualize the latent space correctly. Simply using TSNE just does not make any sense in my experiment.

**Comment by DinSangrasi** [comment]
R u from China?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zhangdan8962** [comment]
Yep!
