### ISSUE TITLE
Missing l2-normalization in the embedding function of ResNet(dim=2048)

### ISSUE THREAD

**Issue by bastian1209** [HobbitLong/SupContrast#48]
Hi, thank you for your easy and clear implementation of "Supervised Contrastive Learning".

While reading the original paper and comparing code between the original repository of Google Research(https://github.com/google-research/google-research/blob/master/supcon/models.py) and yours, I became to have a question. 

As noted in the original paper, before fed into the projection head, the output of the encoder should be l2-normalized, however, I couldn't find any l2-normalization process in your SupConResNet implementation in resnet_big.py.

Is there any meaningful performance difference between yours and the original paper due to this?

**Comment by LuuYin** [comment]
Same question
