### ISSUE TITLE
projection head

### ISSUE THREAD

**Issue by arjung128** [HobbitLong/SupContrast#56]
The paper says "we discard Proj(·) at the end of contrastive training." 

However, based on the code and the commands you have provided to reproduce the results, it seems like the projection head is not discarded in stage 2, but rather loaded in [here](https://github.com/HobbitLong/SupContrast/blob/master/main_linear.py#L126). Is that correct, or am I missing something?

Thank you very much for making this work open source!

**Comment by HobbitLong** [comment]
Hi, @arjung128,

I loaded the weights of projection head, but actually did not use it. See [here](https://github.com/HobbitLong/SupContrast/blob/master/main_linear.py#L153-L156).
