### ISSUE TITLE
Is there a big difference between one-stage and two-stage training? 

### ISSUE THREAD

**Issue by TianQi-777** [HobbitLong/SupContrast#6]
I am a beginner in contrastive learning. I have one question.

Why isn't supervised contrastive loss trained as a regular term with a classifier(with cross-entropy)? What are the benefits of this two-stage training compared with one-stage training?

Look forward to your reply.

**Comment by HobbitLong** [comment]
@TianQi-777, I think it can be.

The point in the SupCon paper is to see how single `supervised contrastive loss` could work. Mixing them together makes the contribution of contrastive loss unclear. But in practice you can put them together and see.

**Comment by TianQi-777** [comment]
Ok, thanks for your prompt reply.

**Comment by DevinCheung** [comment]
@HobbitLong @TianQi-777 Hi, have you tried jointly training (SupCon Loss & CE Loss)? How is the result compared with the two-stage training? Thanks!
