### ISSUE TITLE
About multi-crop strategy.

### ISSUE THREAD

**Issue by MenghaoGuo** [HobbitLong/SupContrast#66]
Hi @HobbitLong , 

Thank you for your inspiring work.

I want to know did you attempt multi-crop strategy like SWaV in your experiments ?  And do you think it will work well under the supervised setting ?

Thanks.

**Comment by HobbitLong** [comment]
We did not try (because SupCon is a work prior to SwAV). I am not sure how the multi-crop strategy would work for SupCon.
