### ISSUE TITLE
Input image resolution for ImageNet

### ISSUE THREAD

**Issue by littleredxh** [HobbitLong/SupContrast#74]
Hi,

I rerun the repo code with my 2 x 32GB V100 GPU. 

If I use 224 by 224 size image, my GPU only can fit 10 images in a batch totally. 

What is the resolution you use in your paper for ImageNet?

**Comment by HobbitLong** [comment]
Hi, @littleredxh,

I used 224x224, it sounds a bug to me if you can fit only 10 images with 2x32GB v100. I suppose your devices could support a batch size of 128 (a rough estimation).

**Comment by Lin-xuejuan-an** [comment]
hi, @littleredxh  May I ask what pre-traine model you are using？

**Comment by littleredxh** [comment]
@Lin-xuejuan-an I am using resnet50

**Comment by littleredxh** [comment]
@HobbitLong I replace the resnet50 in your resnet_big.py with the official one. Then the problem is fixed

**Comment by Lin-xuejuan-an** [comment]
@littleredxh OK, thank you very much for your reply ！

**Comment by lmq150051** [comment]
@littleredxh  I also meet the same problem. Do you only replace the  reset in the reset_big.py with the official one to fixed the problem? Do you mind sharing the new code with me?

**Comment by littleredxh** [comment]
@lmq150051 Yes, just replace the official ResNet with reset_big.py.

**Comment by HobbitLong** [comment]
@littleredxh , I see the problem. The first conv layer of `resnet_big.py` is adapted for CIFAR-10/100, by changing the kernel size to 3 and stride to 1. If `resnet_big.py` is directly applied to ImageNet images with 224 inputs, it will create a very large feature maps that occupy very heavy memory.

**Comment by Angelina1996** [comment]
> Hi,
> 
> I rerun the repo code with my 2 x 32GB V100 GPU.
> 
> If I use 224 by 224 size image, my GPU only can fit 10 images in a batch totally.
> 
> What is the resolution you use in your paper for ImageNet?

Dear hong-xuan,
I am wondering if you would mind sharing the code for the imagenet dataset on my email please,
My email is : robertangelina92@gmail.com

Cheers
